// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/kron.proto

package kronstub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kron_Ready_FullMethodName = "/kronstub.Kron/Ready"
	Kron_Band_FullMethodName  = "/kronstub.Kron/Band"
)

// KronClient is the client API for Kron service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// cells stream
type KronClient interface {
	// get ready
	Ready(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*Cell, error)
	// returns stream of cells
	Band(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Cell], error)
}

type kronClient struct {
	cc grpc.ClientConnInterface
}

func NewKronClient(cc grpc.ClientConnInterface) KronClient {
	return &kronClient{cc}
}

func (c *kronClient) Ready(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*Cell, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cell)
	err := c.cc.Invoke(ctx, Kron_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kronClient) Band(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Cell], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kron_ServiceDesc.Streams[0], Kron_Band_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmptyReq, Cell]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kron_BandClient = grpc.ServerStreamingClient[Cell]

// KronServer is the server API for Kron service.
// All implementations must embed UnimplementedKronServer
// for forward compatibility.
//
// cells stream
type KronServer interface {
	// get ready
	Ready(context.Context, *EmptyReq) (*Cell, error)
	// returns stream of cells
	Band(*EmptyReq, grpc.ServerStreamingServer[Cell]) error
	mustEmbedUnimplementedKronServer()
}

// UnimplementedKronServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKronServer struct{}

func (UnimplementedKronServer) Ready(context.Context, *EmptyReq) (*Cell, error) {
	return nil, status.Error(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedKronServer) Band(*EmptyReq, grpc.ServerStreamingServer[Cell]) error {
	return status.Error(codes.Unimplemented, "method Band not implemented")
}
func (UnimplementedKronServer) mustEmbedUnimplementedKronServer() {}
func (UnimplementedKronServer) testEmbeddedByValue()              {}

// UnsafeKronServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KronServer will
// result in compilation errors.
type UnsafeKronServer interface {
	mustEmbedUnimplementedKronServer()
}

func RegisterKronServer(s grpc.ServiceRegistrar, srv KronServer) {
	// If the following call panics, it indicates UnimplementedKronServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kron_ServiceDesc, srv)
}

func _Kron_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KronServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kron_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KronServer).Ready(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kron_Band_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KronServer).Band(m, &grpc.GenericServerStream[EmptyReq, Cell]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kron_BandServer = grpc.ServerStreamingServer[Cell]

// Kron_ServiceDesc is the grpc.ServiceDesc for Kron service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kron_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kronstub.Kron",
	HandlerType: (*KronServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ready",
			Handler:    _Kron_Ready_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Band",
			Handler:       _Kron_Band_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/kron.proto",
}
