// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: kron.proto

package kronstub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty request band of cells
type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_kron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_kron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_kron_proto_rawDescGZIP(), []int{0}
}

// Cell for multi dimensional analysis
type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Val           int32                  `protobuf:"zigzag32,2,opt,name=val,proto3" json:"val,omitempty"`
	Id            *string                `protobuf:"bytes,3,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Cmd           string                 `protobuf:"bytes,4,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Day           int32                  `protobuf:"zigzag32,5,opt,name=day,proto3" json:"day,omitempty"`
	Mdt           *string                `protobuf:"bytes,6,opt,name=mdt,proto3,oneof" json:"mdt,omitempty"`
	Dms           *int64                 `protobuf:"zigzag64,7,opt,name=dms,proto3,oneof" json:"dms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_kron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_kron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_kron_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Cell) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *Cell) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Cell) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Cell) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Cell) GetMdt() string {
	if x != nil && x.Mdt != nil {
		return *x.Mdt
	}
	return ""
}

func (x *Cell) GetDms() int64 {
	if x != nil && x.Dms != nil {
		return *x.Dms
	}
	return 0
}

var File_kron_proto protoreflect.FileDescriptor

const file_kron_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"kron.proto\x12\bkronstub\"\n" +
	"\n" +
	"\bEmptyReq\"\xaa\x01\n" +
	"\x04Cell\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x10\n" +
	"\x03val\x18\x02 \x01(\x11R\x03val\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x10\n" +
	"\x03cmd\x18\x04 \x01(\tR\x03cmd\x12\x10\n" +
	"\x03day\x18\x05 \x01(\x11R\x03day\x12\x15\n" +
	"\x03mdt\x18\x06 \x01(\tH\x01R\x03mdt\x88\x01\x01\x12\x15\n" +
	"\x03dms\x18\a \x01(\x12H\x02R\x03dms\x88\x01\x01B\x05\n" +
	"\x03_idB\x06\n" +
	"\x04_mdtB\x06\n" +
	"\x04_dms2e\n" +
	"\x04Kron\x12-\n" +
	"\x05Ready\x12\x12.kronstub.EmptyReq\x1a\x0e.kronstub.Cell\"\x00\x12.\n" +
	"\x04Band\x12\x12.kronstub.EmptyReq\x1a\x0e.kronstub.Cell\"\x000\x01B\fZ\n" +
	".;kronstubb\x06proto3"

var (
	file_kron_proto_rawDescOnce sync.Once
	file_kron_proto_rawDescData []byte
)

func file_kron_proto_rawDescGZIP() []byte {
	file_kron_proto_rawDescOnce.Do(func() {
		file_kron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kron_proto_rawDesc), len(file_kron_proto_rawDesc)))
	})
	return file_kron_proto_rawDescData
}

var file_kron_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kron_proto_goTypes = []any{
	(*EmptyReq)(nil), // 0: kronstub.EmptyReq
	(*Cell)(nil),     // 1: kronstub.Cell
}
var file_kron_proto_depIdxs = []int32{
	0, // 0: kronstub.Kron.Ready:input_type -> kronstub.EmptyReq
	0, // 1: kronstub.Kron.Band:input_type -> kronstub.EmptyReq
	1, // 2: kronstub.Kron.Ready:output_type -> kronstub.Cell
	1, // 3: kronstub.Kron.Band:output_type -> kronstub.Cell
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kron_proto_init() }
func file_kron_proto_init() {
	if File_kron_proto != nil {
		return
	}
	file_kron_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kron_proto_rawDesc), len(file_kron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kron_proto_goTypes,
		DependencyIndexes: file_kron_proto_depIdxs,
		MessageInfos:      file_kron_proto_msgTypes,
	}.Build()
	File_kron_proto = out.File
	file_kron_proto_goTypes = nil
	file_kron_proto_depIdxs = nil
}
